import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import Navbar from "@/components/nav";
import CustomSidebarTrigger from "@/components/nav/sidebar-trigger";
import { SidebarProvider } from "@/components/ui/sidebar";
import ProtectRoute from "@/components/protected-route";

const muslish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "learning Django - Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${muslish.variable} antialiased`}>
        <Toaster />
        <SidebarProvider>
          <Navbar />
          <ProtectRoute />
          <CustomSidebarTrigger />
          <main className="flex flex-col w-full items-center">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
