import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const muslish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "learning Django - Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${muslish.variable} antialiased`}>{children}</body>
    </html>
  );
}
